apiVersion: v1
kind: Service
metadata:
  name: dagster-postgres
spec:
  # direct access to the pod from within the cluster, no load balancing
  selector:
    app: dagster-postgres
  ports:
  - protocol: TCP
    port: 5432
