apiVersion: apps/v1
kind: Deployment
metadata:
  name: cask
spec:
  selector:
    matchLabels:
      app: cask
  template:
    metadata:
      labels:
        app: cask
    spec:
      containers:
      - name: service
        image: us-west1-docker.pkg.dev/digital-ucdavis-edu/pub/caskfs:main
        imagePullPolicy: Always
        command: ["cask", "serve"]
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
        env:
          - name: CASKFS_WEBAPP_PATH_PREFIX
            value: /cask
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: postgres-password
        volumeMounts:
          - name: caskfs-volume-claim
            mountPath: /opt/cache
        readinessProbe:
          httpGet:
            path: /cask
            port: 3001
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 1
      volumes:
      - name: caskfs-volume-claim
        persistentVolumeClaim:
          claimName: caskfs
